version: "1"
rules:                      # Array of rules
  - base: release_candidate            # Required. Target branch
    upstream: ikasumiwt:master    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - ikasumiwt,ikasumitest
    reviewers:              # Optional
      - ikasumiwt,ikasumitest
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - ikasumiwt
  - base: dev            # Required. Target branch
    upstream: ikasumiwt:release_candidate    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - ikasumiwt,ikasumitest
    reviewers:              # Optional
      - ikasumiwt,ikasumitest
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - ikasumiwt
label: ":thinking_face: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict